server:
  port: 8093
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.201.111.28:3306/totem?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456

dubbo:
  scan:
    basePackages: com.xiaoniu
  application:
    name: provider-comment
  registry:
    address: zookeeper://192.168.192.129:2181?backup=192.168.192.129:2182,192.168.192.129:2183
  protocol:
    name: dubbo
    port: 20881

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.xiaoniu.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.xiaoniu.mapper: debug